gcp_region      = "us-central1"
project_id      = "[PROJECT_ID]"
pcc_username    = "[COMPUTE_USER]"
pcc_password    = "[COMPUTE_PASS]"
pcc_domain_name = "[CONSOLE_DOMAIN_NAME]"
image_name      = "ubuntu-2004-lts-arm64" 